fond-of-kudu/fond-of-kudu

bundles/checkout-rest-api-country-connector/src/FondOfKudu/Shared/CheckoutRestApiCountryConnector/Transfer/checkout_rest_api_country_connector.transfer.xml
composer.json
dandelion.json

The spelling in the transfer.xml does not affect the PHP code, but it throws an error when creating and merging the transfer objects.

chore: checkout rest api country connector

---

bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Glue/CheckoutRestApiCountryConnector/CheckoutRestApiCountryConnectorFactoryTest.php
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Glue/CheckoutRestApiCountryConnector/Dependency/Client/CheckoutRestApiCountryConnectorToGlossaryStorageClientBridgeTest.php
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Glue/CheckoutRestApiCountryConnector/Dependency/Client/CheckoutRestApiCountryConnectorToLocaleClientBridgeTest.php
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Glue/CheckoutRestApiCountryConnector/Plugin/CheckoutRestApi/CountryCheckoutDataResponseMapperPluginTest.php
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Glue/CheckoutRestApiCountryConnector/Processor/Mapper/CountryMapperTest.php
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Zed/CheckoutRestApiCountryConnector/Business/CheckoutRestApiCountryConnectorBusinessFactoryTest.php
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Zed/CheckoutRestApiCountryConnector/Business/CheckoutRestApiCountryConnectorFacadeTest.php
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Zed/CheckoutRestApiCountryConnector/Business/Expander/CheckoutDataExpanderTest.php
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Zed/CheckoutRestApiCountryConnector/Communication/Plugin/CheckoutRestApi/CountryCheckoutDataExpanderPluginTest.php
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Zed/CheckoutRestApiCountryConnector/Dependency/Facade/CheckoutRestApiCountryConnectorToCountryFacadeBridgeTest.php
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Zed/CheckoutRestApiCountryConnector/Dependency/Facade/CheckoutRestApiCountryConnectorToProductCountryRestrictionCheckoutConnectorFacadeBridgeTest.php
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Zed/CheckoutRestApiCountryConnector/Dependency/Facade/CheckoutRestApiCountryConnectorToStoreFacadeBridgeTest.php
bundles/checkout-rest-api-country-connector/tests/_bootstrap.php
dandelion.json

- unit tests zed-layer
- unit tests glue-layer
- increase version to 1.0.0

chore: checkout-rest-api-country-connector

---

bundles/product-image-storage-connector/.github/workflows/main.yml
bundles/product-image-storage-connector/.gitignore
bundles/product-image-storage-connector/LICENSE
bundles/product-image-storage-connector/Makefile
bundles/product-image-storage-connector/README.md
bundles/product-image-storage-connector/codeception.yml
bundles/product-image-storage-connector/composer.json
bundles/product-image-storage-connector/src/FondOfKudu/Client/ProductImageStorageConnector/Expander/ProductViewImageCustomSetsExpander.php
bundles/product-image-storage-connector/src/FondOfKudu/Client/ProductImageStorageConnector/Expander/ProductViewImageExpanderInterface.php
bundles/product-image-storage-connector/src/FondOfKudu/Client/ProductImageStorageConnector/Plugin/ProductViewImageCustomSetExpanderPlugin.php
bundles/product-image-storage-connector/src/FondOfKudu/Client/ProductImageStorageConnector/ProductImageStorageConnectorConfig.php
bundles/product-image-storage-connector/src/FondOfKudu/Client/ProductImageStorageConnector/ProductImageStorageConnectorDependencyProvider.php
bundles/product-image-storage-connector/src/FondOfKudu/Client/ProductImageStorageConnector/ProductImageStorageConnectorFactory.php
bundles/product-image-storage-connector/src/FondOfKudu/Shared/ProductImageStorageConnector/Transfer/product_image_storage_connector.transfer.xml
bundles/product-image-storage-connector/tests/_bootstrap.php
composer.json
dandelion.json

- skeleton for module product-image-storage-connector

🧩 Expand ProductAbstractImageStorageTransfer with custom image-sets

---

bundles/checkout-rest-api-country-connector/src/FondOfKudu/Glue/CheckoutRestApiCountryConnector/Processor/Mapper/CountryMapper.php
bundles/checkout-rest-api-country-connector/src/FondOfKudu/Shared/CheckoutRestApiCountryConnector/Transfer/checkout_rest_api_country_connector.transfer.xml
bundles/checkout-rest-api-country-connector/tests/FondOfKudu/Glue/CheckoutRestApiCountryConnector/Processor/Mapper/CountryMapperTest.php
dandelion.json

- add idCountry to CountryRestCheckoutDataResponseAttributes
- unit-test adjusted
- increase version to 1.0.2

chore: add idCountry to response

---

bundles/product-image-storage-connector/src/FondOfKudu/Client/ProductImageStorageConnector/Expander/ProductViewImageCustomSetsExpander.php
bundles/product-image-storage-connector/tests/FondOfKudu/Client/ProductImageStorageConnector/Expander/ProductViewImageCustomSetsExpanderTest.php
dandelion.json

- prevent exception if no image-sets given
- increase module version to 1.0.1
- adjust unit-tests

chore: prevent exception if no image-sets given

---

.github/labeler.yml
bundles/checkout-data-product-country-filter/.github/workflows/main.yml
bundles/checkout-data-product-country-filter/.gitignore
bundles/checkout-data-product-country-filter/LICENSE
bundles/checkout-data-product-country-filter/Makefile
bundles/checkout-data-product-country-filter/README.md
bundles/checkout-data-product-country-filter/codeception.yml
bundles/checkout-data-product-country-filter/composer.json
bundles/checkout-data-product-country-filter/src/FondOfKudu/Shared/CheckoutDataProductCountryFilter/Transfer/checkout_data_product_country_filter.schema.xml
bundles/checkout-data-product-country-filter/src/FondOfKudu/Zed/CheckoutDataProductCountryFilter/Business/CheckoutDataProductCountryFilterBusinessFactory.php
bundles/checkout-data-product-country-filter/src/FondOfKudu/Zed/CheckoutDataProductCountryFilter/Business/CheckoutDataProductCountryFilterFacade.php
bundles/checkout-data-product-country-filter/src/FondOfKudu/Zed/CheckoutDataProductCountryFilter/Business/CheckoutDataProductCountryFilterFacadeInterface.php
bundles/checkout-data-product-country-filter/src/FondOfKudu/Zed/CheckoutDataProductCountryFilter/Business/Filter/CheckoutDataProductCountryFilter.php
bundles/checkout-data-product-country-filter/src/FondOfKudu/Zed/CheckoutDataProductCountryFilter/Business/Filter/CheckoutDataProductCountryFilterInterface.php
bundles/checkout-data-product-country-filter/src/FondOfKudu/Zed/CheckoutDataProductCountryFilter/CheckoutDataProductCountryFilterDependencyProvider.php
bundles/checkout-data-product-country-filter/src/FondOfKudu/Zed/CheckoutDataProductCountryFilter/Communication/Plugin/CheckoutDataProductCountryFilterPlugin.php
bundles/checkout-data-product-country-filter/src/FondOfKudu/Zed/CheckoutDataProductCountryFilter/Dependency/Facade/CheckoutDataProductCountryFilterToProductCountryRestrictionCheckoutConnectorFacadeBridge.php
bundles/checkout-data-product-country-filter/src/FondOfKudu/Zed/CheckoutDataProductCountryFilter/Dependency/Facade/CheckoutDataProductCountryFilterToProductCountryRestrictionCheckoutConnectorFacadeInterface.php
bundles/checkout-data-product-country-filter/tests/_bootstrap.php
composer.json
dandelion.json

- new module provides plugin to filter checkout-data by product/country restrictions

chore: checkout data product country filter

---

bundles/carts-rest-api/src/FondOfKudu/Shared/CartsRestApi/Transfer/carts_rest_api.transfer.xml
bundles/carts-rest-api/src/FondOfKudu/Zed/CartsRestApi/Business/Quote/QuoteResetter.php
dandelion.json

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205506950524017

feat: add reset single to multiple quantity item transfers

---

bundles/carts-rest-api/src/FondOfKudu/Shared/CartsRestApi/Transfer/carts_rest_api.transfer.xml
bundles/carts-rest-api/src/FondOfKudu/Zed/CartsRestApi/Business/Quote/QuoteResetter.php
dandelion.json

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205592323916319

fix: add reset id sales shipment

---

bundles/oms-payone-error/src/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/Error3dSecureConditionPlugin.php
bundles/oms-payone-error/src/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/ErrorInOrderPaymentRequestConditionPlugin.php
bundles/oms-payone-error/src/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/ErrorIssueWithCustomerPaymentMethodConditionPlugin.php
bundles/oms-payone-error/src/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/ErrorOrderAddressConditionPlugin.php
bundles/oms-payone-error/src/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/ErrorPaymentRejectedByThirdPartyConditionPlugin.php
bundles/oms-payone-error/src/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/ErrorPayoneSettingsIncorrectConditionPlugin.php
bundles/oms-payone-error/src/FondOfKudu/Zed/OmsPayoneError/Persistence/OmsPayoneErrorRepository.php
bundles/oms-payone-error/src/FondOfKudu/Zed/OmsPayoneError/Persistence/OmsPayoneErrorRepositoryInterface.php
bundles/oms-payone-error/tests/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/Error3dSecureConditionPluginTest.php
bundles/oms-payone-error/tests/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/ErrorInOrderPaymentRequestConditionPluginTest.php
bundles/oms-payone-error/tests/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/ErrorIssueWithCustomerPaymentMethodConditionPluginTest.php
bundles/oms-payone-error/tests/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/ErrorOrderAddressConditionPluginTest.php
bundles/oms-payone-error/tests/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/ErrorPaymentRejectedByThirdPartyConditionPluginTest.php
bundles/oms-payone-error/tests/FondOfKudu/Zed/OmsPayoneError/Communication/Plugin/Oms/Condition/ErrorPayoneSettingsIncorrectConditionPluginTest.php
codeception.yml
dandelion.json

The plugins can also return 'null' :) 
add unit-tests, increase version

chore: fix null pointer exception

---

dandelion.json

chore: product-api-schedule-price-import

---

bundles/customer-password-updated-at-connector/README.md
bundles/customer-password-updated-at-connector/src/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/CustomerPasswordUpdatedAtConnectorClient.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/CustomerPasswordUpdatedAtConnectorClientInterface.php

- add package-node in readme
- fix client-interface

chore: customer password updated at connector

---

bundles/customer-password-updated-at-connector/src/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/CustomerPasswordUpdatedAtConnectorClient.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/CustomerPasswordUpdatedAtConnectorClientInterface.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/Zed/CustomerPasswordUpdatedAtConnectorStub.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/Zed/CustomerPasswordUpdatedAtConnectorStubInterface.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Shared/CustomerPasswordUpdatedAtConnector/CustomerPasswordUpdatedAtConnectorConstants.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Shared/CustomerPasswordUpdatedAtConnector/Transfer/customer_password_updated_at_connector.transfer.xml
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/Business/Customer/AbstractCustomerModel.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/Business/Customer/CustomerPasswordUpdated.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/Business/Customer/CustomerPasswordUpdatedInterface.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/Business/Customer/CustomerRestorePassword.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/Business/CustomerPasswordUpdatedAtConnectorBusinessFactory.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/Business/CustomerPasswordUpdatedAtConnectorFacade.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/Business/CustomerPasswordUpdatedAtConnectorFacadeInterface.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/Communication/Controller/GatewayController.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/CustomerPasswordUpdatedAtConnectorConfig.php

Changelog/Description
- check if user has updated password

chore: customer password udpated validation

---

bundles/customer-password-updated-at-connector/src/FondOfKudu/Shared/CustomerPasswordUpdatedAtConnector/Code/Messages.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/Business/Customer/CustomerPasswordUpdated.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/Business/Customer/CustomerRestorePassword.php

- decouple from spryker-module
- error handling

chore: customer-password-updated-at-connector

---

bundles/customer-password-updated-at-connector/src/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/CustomerPasswordUpdatedAtConnectorDependencyProvider.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/CustomerPasswordUpdatedAtConnectorFactory.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/Dependency/Client/CustomerPasswordUpdatedAtConnectorToZedRequestClientBridge.php
bundles/customer-password-updated-at-connector/src/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/Dependency/Client/CustomerPasswordUpdatedAtConnectorToZedRequestClientInterface.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/CustomerPasswordUpdatedAtConnectorClientTest.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/CustomerPasswordUpdatedAtConnectorDependencyProviderTest.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/CustomerPasswordUpdatedAtConnectorFactoryTest.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/Dependency/Client/CustomerPasswordUpdatedAtConnectorToZedRequestClientBridgeTest.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Client/CustomerPasswordUpdatedAtConnector/Zed/CustomerPasswordUpdatedAtConnectorStubTest.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Zed/CustomerPasswordChangedAtConnector/Business/Customer/CustomerPasswordUpdatedTest.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Zed/CustomerPasswordChangedAtConnector/Business/Customer/CustomerRestorePasswordTest.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Zed/CustomerPasswordChangedAtConnector/Business/CustomerExpander/CustomerExpanderTest.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Zed/CustomerPasswordChangedAtConnector/Business/CustomerPasswordUpdatedAtConnectorFacadeTest.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Zed/CustomerPasswordChangedAtConnector/Communication/Controller/GatewayControllerTest.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Zed/CustomerPasswordChangedAtConnector/Dependency/Facade/CustomerPasswordUpdatedAtConnectorMailFacadeBridgeTest.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Zed/CustomerPasswordChangedAtConnector/Dependency/QueryContainer/CustomerPasswordUpdatedAtConnectorToCustomerQueryContainerBridgeTest.php
codeception.yml

**Changelog**
- unit tests
- refactor

chore: CustomerPasswordUpdatedAtConnector

---

bundles/customer-password-updated-at-connector/src/FondOfKudu/Shared/CustomerPasswordUpdatedAtConnector/Transfer/customer_password_updated_at_connector.transfer.xml
bundles/customer-password-updated-at-connector/src/FondOfKudu/Zed/CustomerPasswordUpdatedAtConnector/Business/Customer/CustomerPasswordUpdated.php
bundles/customer-password-updated-at-connector/tests/FondOfKudu/Zed/CustomerPasswordChangedAtConnector/Business/Customer/CustomerPasswordUpdatedTest.php
bundles/customers-rest-api-connector/src/FondOfKudu/Glue/CustomersRestApiConnector/CustomersRestApiConnectorConfig.php
bundles/customers-rest-api-connector/src/FondOfKudu/Glue/CustomersRestApiConnector/Processor/Customers/CustomerPasswordUpdatedProcessor.php
bundles/customers-rest-api-connector/src/FondOfKudu/Glue/CustomersRestApiConnector/Processor/Validation/RestApiError.php
bundles/customers-rest-api-connector/src/FondOfKudu/Glue/CustomersRestApiConnector/Processor/Validation/RestApiErrorInterface.php
bundles/customers-rest-api-connector/src/FondOfKudu/Shared/CustomersRestApiConnector/Transfer/customers_rest_api_connector.transfer.xml
bundles/customers-rest-api-connector/tests/FondOfKudu/Glue/CustomersRestApiConnector/Processor/Customers/CustomerPasswordUpdatedProcessorTest.php
dandelion.json

**Changelog:**
- add new flag for user account exists

chore: user account exists

---

bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductAbstractModel.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductAbstractModelInterface.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductConcreteModel.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductConcreteModelInterface.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductHandler.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductHandlerInterface.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/ProductApiSchedulePriceImportBusinessFactory.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/ProductApiSchedulePriceImportFacade.php
bundles/product-api-schedule-price-import/tests/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductAbstractModelTest.php
bundles/product-api-schedule-price-import/tests/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductConcreteModelTest.php
bundles/product-api-schedule-price-import/tests/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductHandlerTest.php
bundles/product-api-schedule-price-import/tests/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/ProductApiSchedulePriceImportFacadeTest.php
dandelion.json

- Extracted methods to break down large methods into smaller, more manageable methods.
- Reduced dependency injection by grouping related dependencies into service classes.
- Added type hints and return types for better type safety.
- Improved naming conventions for methods and variables.
- Removed redundant and duplicate code.

chore: Refactor SchedulePriceProductHandler for improved readability and maintainability

---

bundles/kletties-payment-connector/.github/workflows/main.yml
bundles/kletties-payment-connector/.gitignore
bundles/kletties-payment-connector/LICENSE
bundles/kletties-payment-connector/Makefile
bundles/kletties-payment-connector/README.md
bundles/kletties-payment-connector/codeception.yml
bundles/kletties-payment-connector/composer.json
bundles/kletties-payment-connector/phpcs.xml
bundles/kletties-payment-connector/src/FondOfKudu/Shared/KlettiesPaymentConnector/KlettiesPaymentConnectorConstants.php
bundles/kletties-payment-connector/src/FondOfKudu/Shared/KlettiesPaymentConnector/Transfer/kletties_payment_connector.transfer.xml
bundles/kletties-payment-connector/src/FondOfKudu/Zed/KlettiesPaymentConnector/Business/KlettiesPaymentConnectorBusinessFactory.php
bundles/kletties-payment-connector/src/FondOfKudu/Zed/KlettiesPaymentConnector/Business/KlettiesPaymentConnectorFacade.php
bundles/kletties-payment-connector/src/FondOfKudu/Zed/KlettiesPaymentConnector/Business/KlettiesPaymentConnectorFacadeInterface.php
bundles/kletties-payment-connector/src/FondOfKudu/Zed/KlettiesPaymentConnector/Business/PaymentMethodFilter/KlettiesPaymentMethodFilter.php
bundles/kletties-payment-connector/src/FondOfKudu/Zed/KlettiesPaymentConnector/Business/PaymentMethodFilter/KlettiesPaymentMethodFilterInterface.php
bundles/kletties-payment-connector/src/FondOfKudu/Zed/KlettiesPaymentConnector/Communication/KlettiesPaymentMethodFilterPlugin.php
bundles/kletties-payment-connector/src/FondOfKudu/Zed/KlettiesPaymentConnector/KlettiesPaymentConnectorConfig.php
bundles/kletties-payment-connector/tests/FondOfKudu/Zed/KlettiesPaymentConnector/Business/KlettiesPaymentConnectorBusinessFactoryTest.php
bundles/kletties-payment-connector/tests/FondOfKudu/Zed/KlettiesPaymentConnector/Business/KlettiesPaymentConnectorFacadeTest.php
bundles/kletties-payment-connector/tests/FondOfKudu/Zed/KlettiesPaymentConnector/Business/PaymentMethodFilter/KlettiesPaymentMethodFilterTest.php
bundles/kletties-payment-connector/tests/FondOfKudu/Zed/KlettiesPaymentConnector/Communication/KlettiesPaymentMethodFilterPluginTest.php
bundles/kletties-payment-connector/tests/_bootstrap.php
codeception.yml
composer.json
dandelion.json

- move fond-of-oryx/thirty-five-up-payment-connector to fond-of-kudu/kletties-payment-connector

chore: fond-of-kudu/kletties-payment-connector

---

bundles/jellyfish-kletties/.github/workflows/main.yml
bundles/jellyfish-kletties/.gitignore
bundles/jellyfish-kletties/LICENSE
bundles/jellyfish-kletties/Makefile
bundles/jellyfish-kletties/README.md
bundles/jellyfish-kletties/codeception.yml
bundles/jellyfish-kletties/composer.json
bundles/jellyfish-kletties/phpcs.xml
bundles/jellyfish-kletties/src/FondOfKudu/Shared/JellyfishKletties/Transfer/jellyfish_kletties.transfer.xml
bundles/jellyfish-kletties/src/FondOfKudu/Zed/JellyfishKletties/Business/JellyfishKlettiesBusinessFactory.php
bundles/jellyfish-kletties/src/FondOfKudu/Zed/JellyfishKletties/Business/JellyfishKlettiesFacade.php
bundles/jellyfish-kletties/src/FondOfKudu/Zed/JellyfishKletties/Business/JellyfishKlettiesFacadeInterface.php
bundles/jellyfish-kletties/src/FondOfKudu/Zed/JellyfishKletties/Communication/JellyfishKlettiesCommunicationFactory.php
bundles/jellyfish-kletties/src/FondOfKudu/Zed/JellyfishKletties/Communication/Plugin/JellyfishKlettiesOrderExpanderPlugin.php
bundles/jellyfish-kletties/src/FondOfKudu/Zed/JellyfishKletties/Communication/Plugin/JellyfishKlettiesOrderItemExpanderPostMapPlugin.php
bundles/jellyfish-kletties/src/FondOfKudu/Zed/JellyfishKletties/Dependency/Facade/JellyfishKlettiesToKlettiesFacadeBridge.php
bundles/jellyfish-kletties/src/FondOfKudu/Zed/JellyfishKletties/Dependency/Facade/JellyfishKlettiesToKlettiesFacadeInterface.php
bundles/jellyfish-kletties/src/FondOfKudu/Zed/JellyfishKletties/JellyfishKlettiesConfig.php
bundles/jellyfish-kletties/src/FondOfKudu/Zed/JellyfishKletties/JellyfishKlettiesDependencyProvider.php
bundles/jellyfish-kletties/tests/FondOfKudu/Zed/JellyfishKletties/Communication/JellyfishKlettiesCommunicationFactoryTest.php
bundles/jellyfish-kletties/tests/FondOfKudu/Zed/JellyfishKletties/Communication/Plugin/JellyfishKlettiesOrderExpanderPluginTest.php
bundles/jellyfish-kletties/tests/FondOfKudu/Zed/JellyfishKletties/Communication/Plugin/JellyfishKlettiesOrderItemExpanderPostMapPluginTest.php
bundles/jellyfish-kletties/tests/FondOfKudu/Zed/JellyfishKletties/Dependency/Facade/JellyfishKlettiesToKlettiesFacadeBridgeTest.php
bundles/jellyfish-kletties/tests/FondOfKudu/Zed/JellyfishKletties/JellyfishKlettiesDependencyProviderTest.php
bundles/jellyfish-kletties/tests/_bootstrap.php
codeception.yml
composer.json
dandelion.json

Changelog/Description
- move fond-of-oryx/jellyfish-thirty-five-u to fond-of-kudu/jellyfish-kletties

chore: jellyfish kletties

---

bundles/kletties/src/FondOfKudu/Shared/Kletties/KlettiesConstants.php
bundles/kletties/src/FondOfKudu/Zed/Kletties/KlettiesDependencyProvider.php
dandelion.json

- rename from 35UP to Kletties

chore: update kletties-bundle

---

bundles/jellyfish-kletties/composer.json
bundles/kletties/src/FondOfKudu/Shared/Kletties/KlettiesConstants.php
bundles/kletties/src/FondOfKudu/Zed/Kletties/KlettiesDependencyProvider.php
dandelion.json

**Changelog/Description:**
- fix typo

chore: Kletties packages

---

bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductAbstractModel.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductAbstractModelInterface.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductHandler.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/ProductApiSchedulePriceImportBusinessFactory.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Validator/SpecialPriceAttributesValidator.php
bundles/product-api-schedule-price-import/src/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Validator/SpecialPriceAttributesValidatorInterface.php
bundles/product-api-schedule-price-import/tests/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductAbstractModelTest.php
bundles/product-api-schedule-price-import/tests/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Model/SchedulePriceProductHandlerTest.php
bundles/product-api-schedule-price-import/tests/FondOfKudu/Zed/ProductApiSchedulePriceImport/Business/Validator/SpecialPriceAttributesValidatorTest.php
dandelion.json

- If the SpecialPrice is transmitted with empty fields via the middleware and a ScheduledPrice already exists, it will be deleted
- If a ScheduledPrice already exists but the data for the SpecialPrice has changed, the affected entry will be deleted and a new one will be created.
- If no ScheduledPrice exists and the SpecialPrice attributes are set and valid, a new ScheduledPrice will be created.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208407057311998

chore: update product-api-schedule-price-import

---

bundles/jellyfish-kletties/src/FondOfKudu/Shared/JellyfishKletties/Transfer/jellyfish_kletties.transfer.xml
bundles/kletties/composer.json
bundles/kletties/src/FondOfKudu/Shared/Kletties/Transfer/kletties.transfer.xml
bundles/kletties/src/FondOfKudu/Zed/Kletties/Business/Model/Mapper/KlettiesOrderMapper.php
bundles/kletties/src/FondOfKudu/Zed/Kletties/Communication/Plugin/CartsRestApi/PrintjobCartItemMapperPlugin.php
bundles/kletties/src/FondOfKudu/Zed/Kletties/Persistence/Propel/Schema/fok_kletties.schema.xml
composer.json
dandelion.json

Changelog/Description
- add printjobId to propel schema file and transfer
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1208407057311987

chore: update kletties

---

bundles/kletties/src/FondOfKudu/Shared/Kletties/Transfer/kletties.transfer.xml
dandelion.json

- add missing transfer properties

chore: update kletties bundle
